### ISSUE TITLE
Corrupt image data crashes viewer

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#40]
A dot name structure assignment is illegal when the structure is empty.  Use a subscript
on the structure.

Error in viewerMain>menuInclude_Callback (line 940)
    incData.ID = [handles.date '-' handles.embryoNumber '-' handles.cutNumber '-'
    direction];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('menuInclude_Callback',hObject,eventdata,guidata(hObject))

Error in viewerMain>figure1_WindowKeyPressFcn (line 1100)
    callback(handles.menuInclude, []);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('figure1_WindowKeyPressFcn',hObject,eventdata,guidata(hObject))

 
Error while evaluating figure WindowKeyPressFcn

include
  Columns 1 through 14

     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 15 through 28

     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 29 through 31

     0     0     0

include
  Columns 1 through 14

     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 15 through 28

     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 29 through 31

     0     0     0

A dot name structure assignment is illegal when the structure is empty.  Use a subscript
on the structure.

Error in viewerMain>menuInclude_Callback (line 940)
    incData.ID = [handles.date '-' handles.embryoNumber '-' handles.cutNumber '-'
    direction];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('menuInclude_Callback',hObject,eventdata,guidata(hObject))

Error in viewerMain>figure1_WindowKeyPressFcn (line 1100)
    callback(handles.menuInclude, []);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('figure1_WindowKeyPressFcn',hObject,eventdata,guidata(hObject))

 
Error while evaluating figure WindowKeyPressFcn

include
  Columns 1 through 14

     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 15 through 28

     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 29 through 31

     0     0     0

Export...
Error using xlwrite (line 68)
Java exception occurred:
java.lang.OutOfMemoryError: Java heap space
	at jxl.write.biff.MemoryDataOutput.<init>(MemoryDataOutput.java:56)
	at jxl.write.biff.File.createDataOutput(File.java:101)
	at jxl.write.biff.File.<init>(File.java:86)
	at jxl.write.biff.WritableWorkbookImpl.<init>(WritableWorkbookImpl.java:183)
	at jxl.Workbook.createWorkbook(Workbook.java:302)
	at jxl.Workbook.createWorkbook(Workbook.java:286)
	at mymxl.WriteXL.<init>(WriteXL.java:156)

Error in viewerMain>xxwrite (line 681)
        xlwrite(outName, data);

Error in viewerMain>exportWizard_Callback (line 634)
xxwrite(outputName, [headerLine; data]);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('exportWizard_Callback',hObject,eventdata,guidata(hObject))

 
Error while evaluating uimenu Callback

  Columns 1 through 14

     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 15 through 28

     0     0     0     0     0     0     0     0     0     0     0     0     0     0

  Columns 29 through 31

     0     0     0

Error using drawnow
Insufficient Java heap memory to continue operation

Error in busyDlg (line 43)
    drawnow;

Error in viewerMain>move_selected_point (line 542)
busyDlg(busyOutput);

Error in viewerMain>axUpSpeedVPosition_ButtonDownFcn (line 396)
move_selected_point(closest);
 
Error while evaluating axes ButtonDownFcn

**Comment by clairelbromley** [comment]
It went crazy, I tried to export my data as per usual to save it- but it came up with more errors and produced a corrupted file :(

**Comment by clairelbromley** [comment]
A dot name structure assignment is illegal when the structure is empty.  Use a subscript
on the structure.

Error in viewerMain>menuInclude_Callback (line 940)
    incData.ID = [handles.date '-' handles.embryoNumber '-' handles.cutNumber '-'
    direction];

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('menuInclude_Callback',hObject,eventdata,guidata(hObject))


Error in viewerMain>figure1_WindowKeyPressFcn (line 1100)
    callback(handles.menuInclude, []);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in viewerMain (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in
@(hObject,eventdata)viewerMain('figure1_WindowKeyPressFcn',hObject,eventdata,guidata(hObject))

 
Error while evaluating figure WindowKeyPressFcn

**Comment by clairelbromley** [comment]
this seems to be down to embryo 200815 E4C1
This data can now be found in the shared folder on google drive
/Users/clairebromley/Google Drive/Weird data/Github

**Comment by clairelbromley** [comment]
Fixed! I found a problem in the metadata
